//! Cross-runtime parity checks for the deterministic proposal kernel.
//!
//! The fixture is generated by CPython from the existing proposal path.  It is
//! deliberately data-only so a passing test cannot share an implementation
//! with the Rust code under test.

use temporal_qd_kernel::{
    identity::{
        Side, crossover_pair_candidate_id, crossover_side_candidate_id,
        executable_pair_semantic_sha256, immigrant_side_seed, mutation_candidate_id,
        mutation_step_seed, proposal_seed, proposal_side,
    },
    schedule::{
        MAX_SCHEDULED_PROPOSAL_ORDINAL, PythonRandom, RotatingParentSchedule, ScheduleError,
        explicit_parent_index, is_crossover_slot, mutation_depth_for_seed, scheduled_immigrant,
        scheduled_immigrant_for_accepted_quota, sort_explicit_parent_identities, unbiased_choice,
    },
    selector::selector_index,
};

include!("fixtures/proposal_primitives_oracles.rs");

#[test]
fn canonical_proposal_and_side_identities_match_python() {
    for (_, ordinal, expected) in PROPOSAL_SEEDS {
        assert_eq!(proposal_seed(CONFIG_SHA256, ordinal), expected);
    }

    assert_eq!(proposal_side("alpha").unwrap(), Side::Short);
    assert_eq!(proposal_side(42_u64).unwrap(), Side::Long);
    assert_eq!(
        proposal_side("  \u{2003}🚀 é \u{2003} ").unwrap(),
        Side::Short
    );
    // U+001C/U+001F are stripped by Python but are not in Rust's usual
    // `char::is_whitespace` set.  This guards the explicit compatibility path.
    assert_eq!(proposal_side("\u{001c}axis\u{001f}").unwrap(), Side::Short);

    assert_eq!(
        immigrant_side_seed("alpha", Side::Long),
        "sha256:fbd8bc47bc2b0593cc1c4844937f969613201f9352b315632ad074adbcc5d8b5"
    );
    assert_eq!(
        immigrant_side_seed(42_u64, Side::Short),
        "sha256:e39a473fdb159b616cabb4d8bacc0d44243693f1986846b6015a3b2ff614cd9f"
    );
    assert_eq!(
        immigrant_side_seed("🚀", Side::Long),
        "sha256:a8973811710c4cd45b0433f5434bff3378b7d04e9a8e94b42ebd905c7f96b5e9"
    );
    assert_eq!(
        mutation_step_seed("🚀", 2, "sha256:parent2"),
        "sha256:f1f33a093f248fc32bc382fcb093fcfee1169aac44da18f18eb1960adb63641d"
    );
}

#[test]
fn candidate_and_executable_semantic_identities_match_python() {
    assert_eq!(
        mutation_candidate_id("alpha", "sha256:parent", "replace_exit"),
        MUTATION_CANDIDATE_ID
    );
    assert_eq!(
        crossover_side_candidate_id("alpha", Side::Long),
        CROSSOVER_SIDE_CANDIDATE_ID
    );
    assert_eq!(
        crossover_pair_candidate_id("alpha", "sha256:parent", "sha256:mate"),
        CROSSOVER_PAIR_CANDIDATE_ID
    );
    assert_eq!(
        executable_pair_semantic_sha256("sha256:long", "sha256:short"),
        EXECUTABLE_SEMANTIC_SHA256
    );
}

#[test]
fn rejection_sampled_selector_matches_python_utf8_framing() {
    for (seed, axis, size, expected) in SELECTORS {
        assert_eq!(
            selector_index(seed, axis, size).unwrap(),
            expected,
            "{seed:?}/{axis:?}"
        );
    }
    assert_eq!(selector_index(42_u64, "unicode-🚀", 19).unwrap(), 0);
}

#[test]
fn mutation_buckets_and_parent_schedules_match_python() {
    for (seed, expected_bucket, expected_depth) in MUTATION_DEPTHS {
        assert_eq!(unbiased_choice(seed, 20).unwrap(), expected_bucket);
        assert_eq!(mutation_depth_for_seed(seed).unwrap(), expected_depth);
    }

    for (ordinal, expected) in NORMAL_IMMIGRANT_SCHEDULE.into_iter().enumerate() {
        assert_eq!(
            scheduled_immigrant(true, ordinal as u64, None).unwrap(),
            expected
        );
    }
    assert!(scheduled_immigrant(false, 0, None).unwrap());

    let two_thirds = RotatingParentSchedule::from_counts(3, 2).unwrap();
    assert_ne!(two_thirds.schedule_sha256(), SCHEDULE_SHA256);
    let four_fifths = RotatingParentSchedule::from_counts(5, 4).unwrap();
    for (ordinal, expected_offspring) in ROTATING_FOUR_FIFTHS_OFFSPRING.into_iter().enumerate() {
        assert_eq!(
            !four_fifths.is_immigrant(ordinal as u64).unwrap(),
            expected_offspring
        );
    }

    let mut sparse_offspring = 0_u64;
    let mut sparse_immigrants = 0_u64;
    for _ in 0..128 {
        if scheduled_immigrant_for_accepted_quota(102, 26, sparse_offspring, sparse_immigrants)
            .unwrap()
        {
            sparse_immigrants += 1;
        } else {
            sparse_offspring += 1;
        }
    }
    assert_eq!((sparse_offspring, sparse_immigrants), (102, 26));

    assert!(
        two_thirds
            .is_immigrant(MAX_SCHEDULED_PROPOSAL_ORDINAL)
            .is_ok()
    );
    assert_eq!(
        two_thirds.is_immigrant(u64::MAX),
        Err(ScheduleError::ProposalOrdinalExhausted)
    );
    assert_eq!(
        scheduled_immigrant(true, u64::MAX, Some(two_thirds)),
        Err(ScheduleError::ProposalOrdinalExhausted)
    );

    assert!(is_crossover_slot(false, 6, 2, 1));
    assert!(is_crossover_slot(false, 13, 1, 2));
    assert!(!is_crossover_slot(true, 6, 2, 1));
    assert!(!is_crossover_slot(false, 6, 1, 1));
}

#[test]
fn explicit_parent_ring_is_identity_sorted_and_round_robin() {
    let parents = sort_explicit_parent_identities(["sha256:z", "sha256:a", "sha256:m"]);
    assert_eq!(parents, ["sha256:a", "sha256:m", "sha256:z"]);
    let selected = (0..8)
        .map(|selection| parents[explicit_parent_index(selection, parents.len()).unwrap()].clone())
        .collect::<Vec<_>>();
    assert_eq!(
        selected,
        [
            "sha256:a", "sha256:m", "sha256:z", "sha256:a", "sha256:m", "sha256:z", "sha256:a",
            "sha256:m",
        ]
    );
}

#[test]
fn archive_parent_mt19937_stream_matches_cpython_random() {
    for oracle in RNG_ORACLES {
        assert_eq!(
            PythonRandom::archive_parent_seed_sha256(
                oracle.generation_seed,
                oracle.selection_ordinal,
                oracle.label
            ),
            oracle.seed_material_sha256,
        );
        assert_eq!(
            PythonRandom::archive_parent_seed(
                oracle.generation_seed,
                oracle.selection_ordinal,
                oracle.label
            ),
            oracle.seed,
        );

        let mut random = PythonRandom::from_nonnegative_u64(oracle.seed);
        for expected in oracle.random_bits {
            assert_eq!(random.random().to_bits(), expected);
        }

        let mut random = PythonRandom::from_nonnegative_u64(oracle.seed);
        for (bits, expected) in GETRANDBITS_BOUNDARIES.into_iter().zip(oracle.getrandbits) {
            assert_eq!(random.getrandbits(bits).unwrap(), expected);
        }

        let mut random = PythonRandom::from_nonnegative_u64(oracle.seed);
        for (upper, expected) in RANDBELOW_BOUNDARIES.into_iter().zip(oracle.randbelow) {
            assert_eq!(random.randbelow(upper).unwrap(), expected);
        }
    }
}
